import type {
  Profile,
  GoalCycle,
  ThrustArea,
  GoalSheet,
  Goal,
  Achievement,
  Checkin,
  AuditLog,
} from '@/types';

export const MOCK_USERS: Profile[] = [
  {
    id: 'emp-001',
    full_name: 'Riya Sharma',
    email: 'employee@atomberg.demo',
    role: 'employee',
    department: 'Sales West',
    manager_id: 'mgr-001',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mgr-001',
    full_name: 'Vikram Nair',
    email: 'manager@atomberg.demo',
    role: 'manager',
    department: 'Sales West',
    manager_id: 'admin-001',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'admin-001',
    full_name: 'Priya Mehta',
    email: 'admin@atomberg.demo',
    role: 'admin',
    department: 'HR',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-002',
    full_name: 'Arjun Kapoor',
    email: 'arjun@atomberg.demo',
    role: 'employee',
    department: 'R&D',
    manager_id: 'mgr-001',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-003',
    full_name: 'Neha Gupta',
    email: 'neha@atomberg.demo',
    role: 'employee',
    department: 'Operations',
    manager_id: 'mgr-001',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-004',
    full_name: 'Rohit Desai',
    email: 'rohit@atomberg.demo',
    role: 'employee',
    department: 'Supply Chain',
    manager_id: 'mgr-002',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mgr-002',
    full_name: 'Sunita Rao',
    email: 'sunita@atomberg.demo',
    role: 'manager',
    department: 'Supply Chain',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const MOCK_CYCLE: GoalCycle = {
  id: 'cycle-001',
  name: 'FY 2026-27',
  goal_setting_open: '2026-05-01',
  goal_setting_close: '2026-06-30',
  q1_open: '2026-07-01',
  q1_close: '2026-07-31',
  q2_open: '2026-10-01',
  q2_close: '2026-10-31',
  q3_open: '2027-01-01',
  q3_close: '2027-01-31',
  q4_open: '2027-03-01',
  q4_close: '2027-04-30',
  is_active: true,
};

export const MOCK_THRUST_AREAS: ThrustArea[] = [
  { id: 'ta-01', name: 'Revenue Growth', cycle_id: 'cycle-001', is_active: true },
  { id: 'ta-02', name: 'Cost Reduction', cycle_id: 'cycle-001', is_active: true },
  { id: 'ta-03', name: 'Customer Satisfaction', cycle_id: 'cycle-001', is_active: true },
  { id: 'ta-04', name: 'Safety & Compliance', cycle_id: 'cycle-001', is_active: true },
  { id: 'ta-05', name: 'Operational Excellence', cycle_id: 'cycle-001', is_active: true },
];

export const MOCK_GOAL_SHEETS: GoalSheet[] = [
  {
    id: 'sheet-001',
    employee_id: 'emp-001',
    cycle_id: 'cycle-001',
    status: 'approved',
    submitted_at: '2026-05-10T09:00:00Z',
    approved_at: '2026-05-12T14:30:00Z',
    approved_by: 'mgr-001',
    is_locked: true,
    total_weightage: 100,
    overall_score: 78.5,
  },
  {
    id: 'sheet-002',
    employee_id: 'emp-002',
    cycle_id: 'cycle-001',
    status: 'submitted',
    submitted_at: '2026-05-11T10:00:00Z',
    is_locked: false,
    total_weightage: 100,
  },
  {
    id: 'sheet-003',
    employee_id: 'emp-003',
    cycle_id: 'cycle-001',
    status: 'draft',
    is_locked: false,
    total_weightage: 70,
  },
  {
    id: 'sheet-004',
    employee_id: 'emp-004',
    cycle_id: 'cycle-001',
    status: 'returned',
    submitted_at: '2026-05-09T08:00:00Z',
    return_reason: 'Weightage distribution needs rebalancing. Goal #2 target is too vague.',
    is_locked: false,
    total_weightage: 100,
  },
];

export const MOCK_GOALS: Goal[] = [
  // Riya's goals (sheet-001, approved+locked)
  {
    id: 'g-001',
    sheet_id: 'sheet-001',
    thrust_area_id: 'ta-01',
    title: 'Increase Regional Sales Revenue',
    description: 'Drive Q1-Q4 revenue in West region to ₹50Cr',
    uom_type: 'numeric_min',
    target_value: 5000,
    weightage: 40,
    is_shared: false,
    display_order: 1,
  },
  {
    id: 'g-002',
    sheet_id: 'sheet-001',
    thrust_area_id: 'ta-03',
    title: 'Improve Customer NPS Score',
    description: 'Increase NPS from 42 to 60 by Q4',
    uom_type: 'numeric_min',
    target_value: 60,
    weightage: 25,
    is_shared: false,
    display_order: 2,
  },
  {
    id: 'g-003',
    sheet_id: 'sheet-001',
    thrust_area_id: 'ta-04',
    title: 'Zero Safety Incidents in Team',
    description: 'Maintain zero workplace safety incidents across all team activities',
    uom_type: 'zero',
    weightage: 15,
    is_shared: false,
    display_order: 3,
  },
  {
    id: 'g-004',
    sheet_id: 'sheet-001',
    thrust_area_id: 'ta-05',
    title: 'Launch West Region Distribution Portal',
    description: 'Complete rollout of distributor portal by Q2',
    uom_type: 'timeline',
    target_date: '2026-10-31',
    weightage: 20,
    is_shared: false,
    display_order: 4,
  },
  // Arjun's goals (sheet-002, submitted)
  {
    id: 'g-005',
    sheet_id: 'sheet-002',
    thrust_area_id: 'ta-01',
    title: 'Launch New Fan SKU in 3 Markets',
    uom_type: 'numeric_min',
    target_value: 3,
    weightage: 30,
    is_shared: false,
    display_order: 1,
  },
  {
    id: 'g-006',
    sheet_id: 'sheet-002',
    thrust_area_id: 'ta-02',
    title: 'Reduce Warranty Claims Rate',
    uom_type: 'numeric_max',
    target_value: 1.5,
    weightage: 30,
    is_shared: false,
    display_order: 2,
  },
  {
    id: 'g-007',
    sheet_id: 'sheet-002',
    thrust_area_id: 'ta-05',
    title: 'Complete ISO 9001 Re-certification',
    uom_type: 'timeline',
    target_date: '2026-12-31',
    weightage: 40,
    is_shared: false,
    display_order: 3,
  },
  // Neha's draft goals (sheet-003)
  {
    id: 'g-008',
    sheet_id: 'sheet-003',
    thrust_area_id: 'ta-05',
    title: 'Reduce Order-to-Delivery TAT',
    uom_type: 'numeric_max',
    target_value: 3,
    weightage: 40,
    is_shared: false,
    display_order: 1,
  },
  {
    id: 'g-009',
    sheet_id: 'sheet-003',
    thrust_area_id: 'ta-02',
    title: 'Cut Operational Costs by 8%',
    uom_type: 'numeric_max',
    target_value: 92,
    weightage: 30,
    is_shared: false,
    display_order: 2,
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach-001', goal_id: 'g-001', quarter: 'Q1', actual_value: 1100, status: 'on_track', score: 88, updated_at: '2026-07-25T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-002', goal_id: 'g-001', quarter: 'Q2', actual_value: 2800, status: 'on_track', score: 92, updated_at: '2026-10-28T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-003', goal_id: 'g-002', quarter: 'Q1', actual_value: 48, status: 'on_track', score: 80, updated_at: '2026-07-25T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-004', goal_id: 'g-002', quarter: 'Q2', actual_value: 55, status: 'on_track', score: 91.7, updated_at: '2026-10-28T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-005', goal_id: 'g-003', quarter: 'Q1', actual_value: 0, status: 'completed', score: 100, updated_at: '2026-07-25T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-006', goal_id: 'g-003', quarter: 'Q2', actual_value: 0, status: 'completed', score: 100, updated_at: '2026-10-28T10:00:00Z', updated_by: 'emp-001' },
  { id: 'ach-007', goal_id: 'g-004', quarter: 'Q2', actual_date: '2026-10-25', status: 'completed', score: 100, updated_at: '2026-10-28T10:00:00Z', updated_by: 'emp-001' },
];

export const MOCK_CHECKINS: Checkin[] = [
  {
    id: 'ci-001',
    sheet_id: 'sheet-001',
    manager_id: 'mgr-001',
    quarter: 'Q1',
    comment: 'Riya is on track with revenue targets. NPS improvement is progressing well. Discussed doubling channel partner engagement in Q2.',
    completed_at: '2026-07-28T15:00:00Z',
  },
  {
    id: 'ci-002',
    sheet_id: 'sheet-001',
    manager_id: 'mgr-001',
    quarter: 'Q2',
    comment: 'Strong Q2 performance. Portal launched ahead of schedule. NPS at 55 — excellent. Q3 focus should be on consolidating gains.',
    completed_at: '2026-10-30T16:00:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'al-001',
    entity_type: 'goal',
    entity_id: 'g-001',
    action: 'edit_target',
    actor_id: 'mgr-001',
    actor_name: 'Vikram Nair',
    actor_role: 'manager',
    old_value: { target_value: 4500 },
    new_value: { target_value: 5000 },
    reason: 'Aligned with Q1 sales plan revision',
    created_at: '2026-05-12T14:00:00Z',
  },
  {
    id: 'al-002',
    entity_type: 'goal_sheet',
    entity_id: 'sheet-001',
    action: 'approve',
    actor_id: 'mgr-001',
    actor_name: 'Vikram Nair',
    actor_role: 'manager',
    old_value: { status: 'submitted' },
    new_value: { status: 'approved' },
    created_at: '2026-05-12T14:30:00Z',
  },
  {
    id: 'al-003',
    entity_type: 'goal_sheet',
    entity_id: 'sheet-001',
    action: 'lock',
    actor_id: 'mgr-001',
    actor_name: 'Vikram Nair',
    actor_role: 'manager',
    new_value: { is_locked: true },
    created_at: '2026-05-12T14:30:05Z',
  },
  {
    id: 'al-004',
    entity_type: 'goal_sheet',
    entity_id: 'sheet-004',
    action: 'return',
    actor_id: 'mgr-001',
    actor_name: 'Vikram Nair',
    actor_role: 'manager',
    old_value: { status: 'submitted' },
    new_value: { status: 'returned' },
    reason: 'Weightage distribution needs rebalancing. Goal #2 target is too vague.',
    created_at: '2026-05-10T16:00:00Z',
  },
  {
    id: 'al-005',
    entity_type: 'goal',
    entity_id: 'g-002',
    action: 'unlock',
    actor_id: 'admin-001',
    actor_name: 'Priya Mehta',
    actor_role: 'admin',
    old_value: { is_locked: true },
    new_value: { is_locked: false },
    reason: 'Employee requested correction to NPS baseline figure — verified with manager',
    created_at: '2026-05-15T11:00:00Z',
  },
  {
    id: 'al-006',
    entity_type: 'achievement',
    entity_id: 'ach-001',
    action: 'edit_actual',
    actor_id: 'emp-001',
    actor_name: 'Riya Sharma',
    actor_role: 'employee',
    old_value: { actual_value: 980 },
    new_value: { actual_value: 1100 },
    created_at: '2026-07-25T10:00:00Z',
  },
];

export const MOCK_ORG_COMPLETION = [
  { id: 'emp-001', name: 'Riya Sharma', dept: 'Sales West', manager: 'Vikram Nair', goalSet: true, approved: true, q1Emp: true, q1Mgr: true, q2Emp: true, q2Mgr: true, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
  { id: 'emp-002', name: 'Arjun Kapoor', dept: 'R&D', manager: 'Vikram Nair', goalSet: true, approved: false, q1Emp: false, q1Mgr: false, q2Emp: false, q2Mgr: false, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
  { id: 'emp-003', name: 'Neha Gupta', dept: 'Operations', manager: 'Vikram Nair', goalSet: true, approved: false, q1Emp: false, q1Mgr: false, q2Emp: false, q2Mgr: false, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
  { id: 'emp-004', name: 'Rohit Desai', dept: 'Supply Chain', manager: 'Sunita Rao', goalSet: true, approved: false, q1Emp: false, q1Mgr: false, q2Emp: false, q2Mgr: false, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
  { id: 'emp-005', name: 'Kavya Reddy', dept: 'Marketing', manager: 'Sunita Rao', goalSet: true, approved: true, q1Emp: true, q1Mgr: true, q2Emp: false, q2Mgr: false, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
  { id: 'emp-006', name: 'Aditya Singh', dept: 'Finance', manager: 'Vikram Nair', goalSet: false, approved: false, q1Emp: false, q1Mgr: false, q2Emp: false, q2Mgr: false, q3Emp: false, q3Mgr: false, q4Emp: false, q4Mgr: false },
];

export const MOCK_QOQ_DATA = [
  { quarter: 'Q1', 'Riya Sharma': 88.5, 'Arjun Kapoor': 72.0, 'Neha Gupta': 65.0, 'Rohit Desai': 80.0 },
  { quarter: 'Q2', 'Riya Sharma': 91.2, 'Arjun Kapoor': 78.5, 'Neha Gupta': 70.0, 'Rohit Desai': 82.5 },
  { quarter: 'Q3', 'Riya Sharma': 85.0, 'Arjun Kapoor': 82.0, 'Neha Gupta': 75.0, 'Rohit Desai': 79.0 },
  { quarter: 'Q4', 'Riya Sharma': 93.0, 'Arjun Kapoor': 88.0, 'Neha Gupta': 78.0, 'Rohit Desai': 85.0 },
];

export const MOCK_HEATMAP_DATA = [
  { dept: 'Sales West', Q1: 88, Q2: 91, Q3: 85, Q4: 93 },
  { dept: 'R&D', Q1: 72, Q2: 78, Q3: 82, Q4: 88 },
  { dept: 'Operations', Q1: 65, Q2: 70, Q3: 75, Q4: 78 },
  { dept: 'Supply Chain', Q1: 80, Q2: 82, Q3: 79, Q4: 85 },
  { dept: 'Marketing', Q1: 76, Q2: 81, Q3: 84, Q4: 89 },
  { dept: 'Finance', Q1: 71, Q2: 75, Q3: 79, Q4: 83 },
];

export const MOCK_THRUST_DIST = [
  { name: 'Revenue Growth', value: 35, color: '#FDB813' },
  { name: 'Cost Reduction', value: 20, color: '#1F2937' },
  { name: 'Customer Satisfaction', value: 22, color: '#16A34A' },
  { name: 'Safety & Compliance', value: 10, color: '#DC2626' },
  { name: 'Operational Excellence', value: 13, color: '#9CA3AF' },
];

export const MOCK_MGR_EFFECTIVENESS = [
  { manager: 'Vikram Nair', score: 94, dept: 'Sales West' },
  { manager: 'Sunita Rao', score: 87, dept: 'Supply Chain' },
  { manager: 'Anand Kumar', score: 91, dept: 'R&D' },
  { manager: 'Divya Iyer', score: 76, dept: 'Finance' },
];

export const DEMO_CREDENTIALS = [
  { role: 'Employee', email: 'employee@atomberg.demo', password: 'Demo@1234' },
  { role: 'Manager', email: 'manager@atomberg.demo', password: 'Demo@1234' },
  { role: 'Admin', email: 'admin@atomberg.demo', password: 'Demo@1234' },
];
